### ISSUE TITLE
XOR as the public function is broken.

### ISSUE THREAD

**Issue by micklh** [erose1337/Destiny#1]
The implementation uses xor (instead of add) so the subset sum problem doesn't apply. The subset xor problem is actually what the public encryption depends on, which is not NP-complete and can be solved in O(n^3). Therefore, the homomorphic operation should be addition over Z/2^nZ (i.e. integer addition) instead of addition over GF(2^n) (i.e. binary xor)

**Comment by erose1337** [comment]
This is not difficult to change in regards to the public key part, but it will require a totally different secret key cipher. I do not have a design for such a thing yet. I will keep it in mind, but I have been working on other things lately.

**Comment by erose1337** [comment]
I added a variant that uses integer addition instead of xor

**Comment by erose1337** [comment]
I am pretty sure this variant will require randomized padding, it seems to preserve multiplicative differences

**Comment by micklh** [comment]
There are several points I need to bring up about this new design, and I would not necessarily classify them as "Issues". Will you talk to me on some instant messaging / chat platform? This forum is inappropriate for the kind of short-time feedback we would need to make any reasonable progress from this point.

**Comment by micklh** [comment]
>  it seems to preserve multiplicative differences

This follows from the definition of an additively homomorphic cipher:
Base case:
`2*E(x) = E(x)+E(x) = E(x+x) = E(2*x)`
Induction:
`n*E(x) = E(x)+...+E(x) = E(x+...+x) = E(n*x)`

**Comment by erose1337** [comment]
Oh I see, so this property is always present in an additively homomorphic cipher?

**Comment by erose1337** [comment]
(and thus is not a bug?)

**Comment by micklh** [comment]
Yeah, basically being able to add ciphertexts implies being able to multiply them by a constant.
