### ISSUE TITLE
Subset sum problems generated may not always be difficult.

### ISSUE THREAD

**Issue by micklh** [erose1337/Destiny#2]
There is a non-trivial relationship involving nearly all of the cipher parameters, and even the hamming weight of the message, which may produce subset sum problems with a too-low or too-high (and thus easily solvable) density. For example, the way `integerbased/secretkey.py` is configured, there is a low density attack using lattice methods for any message & encoding with effective hamming weight < 11. This is directly at odds with another issue I'll open though.

**Comment by erose1337** [comment]
when you say effective hamming weight < 11, what does that mean? Where the hamming weight of the ciphertext is < 11? If so, that should never happen: assuming a statistically random output, the minimum weight that should appear in practice should be > 38

**Comment by micklh** [comment]
I've defined the "effective hamming weight" as the number of unique ciphertexts combined with the public function. I've chosen this metric because it is straightforwardly and directly related to nearly all attacks against the scheme. I've called it effective "hamming weight" because it's equal to the hamming weight of the message under any optimal encoding. Now, even ignoring the other open issue where such a high effective hamming weight is a problem, that < 11 is determined by the block size of 8. If you were to increase the block size to 128 then the situation is even worse: any ciphertext with effective hamming weight < 135 becomes an easy case for lattice methods.

**Comment by erose1337** [comment]
let me get this straight: the block size being larger makes the problem worse, not better? 

The block size of the cipher in secretkey.py is actually not 64 bits. It actually operates on arbitrarily sized blocks, in multiples of 8 bits. For example, you can do:

`from secretkey import encrypt, urandom
# bigger
data = bytearray(123)
data[0] = 1
key = bytearray(urandom(123))
print encrypt(data, key)
# smaller
data = bytearray(4)
data[0] = 1
key = bytearray(urandom(4))
print encrypt(data, key)`

**Comment by micklh** [comment]
> let me get this straight: the block size being larger makes the problem worse, not better?

Yes. Exactly. Larger the blocks, the easier for the lattice algorithms. Also, more random padding has the same effect, it reduces the density of the subset sum problems into the range where algorithms like LLL can solve it.

Also, I already knew that the block size is variable, and that has been completely considered in my analysis... long before I told you about the concept on discord lol
